---
- block:

  - name: yum dependencies
    yum: name={{ item }} state=present
    with_items:
      - pygpgme
      - yum-utils

  - name: Wavefront yum repo
    template:
      src: wavefront.repo.j2
      dest: /etc/yum.repos.d/wavefront-proxy.repo
      owner: root
      group: root
      mode: 0644


  - name: install Wavefront Proxy
    yum: name=wavefront-proxy state=latest

  tags:
    - wavefront-proxy-repo
    - wavefront-proxy
